apiVersion: v1
kind: Pod
metadata:
  name: client
  namespace: ns
spec:
  serviceAccountName: client
  containers:
    - name: client
      image: giantswarm/tiny-tools:3.9
      command:
        - "sleep"
        - "36000"