apiVersion: v1
kind: Pod
metadata:
  name: server
  namespace: ns
  labels:
    app: server
spec:
  serviceAccountName: server
  containers:
    - name: server
      image: containous/whoamitcp
      imagePullPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: server
  namespace: ns
  labels:
    app: server
  annotations:
    maesh.containo.us/traffic-type: tcp
spec:
  type: ClusterIP
  ports:
    - port: 8080
      name: server
  selector:
    app: server
